server:
  port: 8080
spring:
  datasource:
    # url: jdbc:mariadb://localhost:3307/testdb
    # driver-class-name: org.mariadb.jdbc.Driver
    # username: root
    # password: ENC(Nh1Ye4qGl7bp+B8/C6ggbg==) #Jasypt로 암호화한 형태
    hikari:
      primary:
        driver-class-name: org.mariadb.jdbc.Driver
        jdbc-url: jdbc:mariadb://localhost:3307/testdb
        username: root
        password: ENC(Nh1Ye4qGl7bp+B8/C6ggbg==)
      secondary:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1234
  jpa:
    # database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
    open-in-view: false

logging:
  level:
    root: INFO
    dev.ohhoonim.demo.mapper: TRACE

file:
  upload:
    rootpath: /home/upload
